---
baseurl: "https://www.spacesh.com/"
DefaultContentLanguage: "zh-cn"
hasCJKLanguage: true
languageCode: "zh-cn"
title: "River's Site"
theme: "beautifulhugo"
metaDataFormat: "yaml"
algolia:
  index: "hugoblogloveit"
  key: "d3ef25fc7cb90a144ea0139748e4cf6b"
  appID: "EO42BFKWB5"
---
