---
baseURL: "http://zhaoqiangcn.github.io/BlogHugoLoveit/"
languageCode: "zh"
title: "zhaoqiang's blog"
theme: "LoveIt"
description: "一个记录个人工作、生活的blog"

#下面信息填写自己的algolia信息
algolia:
  index: "www.nashome.cn"
  key: "acbdc102e2c95f016d423fa03690923d"
  appID: "EO42BFKWB5"
---